
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Jussara Andrade
 */
public class Livros extends javax.swing.JFrame {

    /**
     * Creates new form Filme
     */
    public Livros() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public void CadastroLivros() {

        try {

            int campos1 = Integer.parseInt(jTextFieldCadastroLivrosNome.getText());
            JOptionPane.showMessageDialog(null, "Por favor, digite somente letras", "Erro", JOptionPane.ERROR_MESSAGE);
            jTextFieldCadastroLivrosNome.setText("");

        } catch (Exception error) {

        }
        try {

            int campos2 = Integer.parseInt(jTextFieldCadastroLivrosAutor.getText());
            JOptionPane.showMessageDialog(null, "Por favor, digite somente letras", "Erro", JOptionPane.ERROR_MESSAGE);
            jTextFieldCadastroLivrosAutor.setText("");
        } catch (Exception error) {

            if (jTextFieldCadastroLivrosNome.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Por favor, digite o Nome!", "Erro", JOptionPane.ERROR_MESSAGE);

            } else if (jTextFieldCadastroLivrosAutor.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Por favor, digite o nome Autor", "Erro", JOptionPane.ERROR_MESSAGE);
            } else if (jComboBoxCategoria.getSelectedItem().toString().equals("Selecione...")) {
                JOptionPane.showMessageDialog(null, "Por favor, selecione a Categoria de Livros! ", "Erro", JOptionPane.ERROR_MESSAGE);

            } else if (jTextFieldPaginas.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Por favor, digite a página do livros!", "Erro", JOptionPane.ERROR_MESSAGE);
            } else if (jTextFieldEditora.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Por favor, digite o nome da Editora", "Erro", JOptionPane.ERROR_MESSAGE);
            } else if (jRadioButtonEditora.isSelected()) {

                JOptionPane.showMessageDialog(null, "Cadastro Editora efeutado com sucesso! "
                        + "\n\nEditora: " + jTextFieldEditora.getText());

            } else if (!jRadioButtonLivros.isSelected() && !jRadioButtonEditora.isSelected()) {

                JOptionPane.showMessageDialog(null, "Por favor, selecione a opção Livro ou Editora", "Erro", JOptionPane.ERROR_MESSAGE);

            } else if (jRadioButtonLivros.isSelected()) {

                JOptionPane.showMessageDialog(null, "Cadastro Livro efetuado com sucesso! "
                        + "\n\nNome: " + jTextFieldCadastroLivrosNome.getText()
                        + "\nAutor: " + jTextFieldCadastroLivrosAutor.getText()
                        + "\nCategoria: " + jComboBoxCategoria.getSelectedItem()
                        + "\nEditora: " + jTextFieldEditora.getText()
                        + "\nPáginas: " + jTextFieldPaginas.getText());

            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelCadastroLivros = new javax.swing.JPanel();
        jLabelCadastroLivrosNome = new javax.swing.JLabel();
        jTextFieldCadastroLivrosNome = new javax.swing.JTextField();
        jLabelCadastroLivrosAutor = new javax.swing.JLabel();
        jTextFieldCadastroLivrosAutor = new javax.swing.JTextField();
        jLabelCadastroLivrosCategoria = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jLabelPaginas = new javax.swing.JLabel();
        jRadioButtonLivros = new javax.swing.JRadioButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonOk = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldEditora = new javax.swing.JTextField();
        jRadioButtonEditora = new javax.swing.JRadioButton();
        jTextFieldPaginas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelCadastroLivros.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro Livros"));

        jLabelCadastroLivrosNome.setText("Nome:");

        jLabelCadastroLivrosAutor.setText("Autor:");

        jLabelCadastroLivrosCategoria.setText("Categoria:");

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Aventura", "Drama", "Romance", "Fantasia", "Terror", "Comédia", "Biografia", "Didático" }));

        jLabelPaginas.setText("Páginas:");

        buttonGroup1.add(jRadioButtonLivros);
        jRadioButtonLivros.setText("Livros");

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Editora:");

        buttonGroup1.add(jRadioButtonEditora);
        jRadioButtonEditora.setText("Editora");

        javax.swing.GroupLayout jPanelCadastroLivrosLayout = new javax.swing.GroupLayout(jPanelCadastroLivros);
        jPanelCadastroLivros.setLayout(jPanelCadastroLivrosLayout);
        jPanelCadastroLivrosLayout.setHorizontalGroup(
            jPanelCadastroLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLivrosLayout.createSequentialGroup()
                .addGroup(jPanelCadastroLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLivrosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelCadastroLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroLivrosLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEditora))
                            .addGroup(jPanelCadastroLivrosLayout.createSequentialGroup()
                                .addComponent(jLabelCadastroLivrosNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCadastroLivrosNome, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelCadastroLivrosLayout.createSequentialGroup()
                                .addComponent(jLabelCadastroLivrosCategoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelCadastroLivrosLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadastroLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroLivrosLayout.createSequentialGroup()
                                .addComponent(jLabelCadastroLivrosAutor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCadastroLivrosAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCadastroLivrosLayout.createSequentialGroup()
                                .addComponent(jLabelPaginas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonCancelar)))
                    .addGroup(jPanelCadastroLivrosLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jRadioButtonLivros)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonEditora)))
                .addGap(20, 20, 20))
        );
        jPanelCadastroLivrosLayout.setVerticalGroup(
            jPanelCadastroLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLivrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroLivrosNome)
                    .addComponent(jTextFieldCadastroLivrosNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCadastroLivrosAutor)
                    .addComponent(jTextFieldCadastroLivrosAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroLivrosCategoria)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPaginas)
                    .addComponent(jTextFieldPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCadastroLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonLivros)
                    .addComponent(jRadioButtonEditora))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtonOk)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadastroLivros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadastroLivros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        jTextFieldCadastroLivrosAutor.setText("");
        jTextFieldCadastroLivrosNome.setText("");
        jTextFieldEditora.setText("");
        jComboBoxCategoria.setSelectedIndex(0);
        jTextFieldPaginas.setText("");
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        JOptionPane.showMessageDialog(null, "Operação cancelada!");
        System.exit(0);

    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        CadastroLivros();
    }//GEN-LAST:event_jButtonOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Livros.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Livros.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Livros.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Livros.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Livros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCadastroLivrosAutor;
    private javax.swing.JLabel jLabelCadastroLivrosCategoria;
    private javax.swing.JLabel jLabelCadastroLivrosNome;
    private javax.swing.JLabel jLabelPaginas;
    private javax.swing.JPanel jPanelCadastroLivros;
    private javax.swing.JRadioButton jRadioButtonEditora;
    private javax.swing.JRadioButton jRadioButtonLivros;
    private javax.swing.JTextField jTextFieldCadastroLivrosAutor;
    private javax.swing.JTextField jTextFieldCadastroLivrosNome;
    private javax.swing.JTextField jTextFieldEditora;
    private javax.swing.JTextField jTextFieldPaginas;
    // End of variables declaration//GEN-END:variables
}
