
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Jussara Andrade
 */
public class Jogo extends javax.swing.JFrame {

    int escolhaComputador;
    int pontosComputador = 0;

    String jogo, erro;

    public Jogo() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public void jogo() {

        switch (escolhaComputador) {
            case 1:
                break;
            case 2:
                break;
            case 3:
                break;
        }
    }

    public void validador() {
        if (jTextFieldPartida1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo 1 está vazio", "Erro", JOptionPane.ERROR_MESSAGE);
        } else if (jTextFieldPartida2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo 2 está vazio", "Erro", JOptionPane.ERROR_MESSAGE);
        } else if (jTextFieldPartida3.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo 3 está vazio", "Erro", JOptionPane.ERROR_MESSAGE);
        } else if (jTextFieldPartida4.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo 4 está vazio", "Erro", JOptionPane.ERROR_MESSAGE);
        } else if (jTextFieldPartida5.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo 5 está vazio", "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelJanela = new javax.swing.JPanel();
        jLabelPergunta = new javax.swing.JLabel();
        jTextFieldPartida1 = new javax.swing.JTextField();
        jTextFieldPartida2 = new javax.swing.JTextField();
        jTextFieldPartida3 = new javax.swing.JTextField();
        jTextFieldPartida4 = new javax.swing.JTextField();
        jTextFieldPartida5 = new javax.swing.JTextField();
        jLabelPartida1 = new javax.swing.JLabel();
        jLabelPartida2 = new javax.swing.JLabel();
        jLabelPartida3 = new javax.swing.JLabel();
        jLabelPartida4 = new javax.swing.JLabel();
        jLabelPartida5 = new javax.swing.JLabel();
        jButtonLimpar = new javax.swing.JButton();
        jButtonJogar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelJanela.setBorder(javax.swing.BorderFactory.createTitledBorder("Jokenpo"));

        jLabelPergunta.setText("Escolha as opções (1 - Pedra, 2 -  Papel, 3 - Tesoura)?");

        jTextFieldPartida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPartida1ActionPerformed(evt);
            }
        });

        jLabelPartida1.setText("Partida 1:");

        jLabelPartida2.setText("Partida 2:");

        jLabelPartida3.setText("Partida 3:");

        jLabelPartida4.setText("Partida 4:");

        jLabelPartida5.setText("Partida 5:");

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonJogar.setText("Jogar");
        jButtonJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJogarActionPerformed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelJanelaLayout = new javax.swing.GroupLayout(jPanelJanela);
        jPanelJanela.setLayout(jPanelJanelaLayout);
        jPanelJanelaLayout.setHorizontalGroup(
            jPanelJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJanelaLayout.createSequentialGroup()
                .addGroup(jPanelJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPergunta)
                    .addGroup(jPanelJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelJanelaLayout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelJanelaLayout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addGroup(jPanelJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanelJanelaLayout.createSequentialGroup()
                                    .addComponent(jLabelPartida5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldPartida5))
                                .addGroup(jPanelJanelaLayout.createSequentialGroup()
                                    .addComponent(jLabelPartida4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldPartida4))
                                .addGroup(jPanelJanelaLayout.createSequentialGroup()
                                    .addComponent(jLabelPartida3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldPartida3))
                                .addGroup(jPanelJanelaLayout.createSequentialGroup()
                                    .addComponent(jLabelPartida2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldPartida2))
                                .addGroup(jPanelJanelaLayout.createSequentialGroup()
                                    .addComponent(jLabelPartida1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldPartida1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanelJanelaLayout.setVerticalGroup(
            jPanelJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJanelaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelPergunta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPartida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPartida1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPartida2)
                    .addComponent(jTextFieldPartida2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanelJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPartida3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPartida3))
                .addGap(9, 9, 9)
                .addGroup(jPanelJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPartida4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPartida4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPartida5)
                    .addComponent(jTextFieldPartida5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanelJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtonJogar)
                    .addComponent(jButtonSair))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelJanela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelJanela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        jTextFieldPartida1.setText("");
        jTextFieldPartida2.setText("");
        jTextFieldPartida3.setText("");
        jTextFieldPartida4.setText("");
        jTextFieldPartida5.setText("");
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jTextFieldPartida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPartida1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPartida1ActionPerformed

    private void jButtonJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJogarActionPerformed
        validador();
        Random gerador = new Random();
        try {
            int partida1 = Integer.parseInt(jTextFieldPartida1.getText());
            int partida2 = Integer.parseInt(jTextFieldPartida2.getText());
            int partida3 = Integer.parseInt(jTextFieldPartida3.getText());
            int partida4 = Integer.parseInt(jTextFieldPartida4.getText());
            int partida5 = Integer.parseInt(jTextFieldPartida5.getText());

            escolhaComputador = gerador.nextInt(3) + 1;

            //Comparar se foi empatado caso o ponto esteja igual ao outro no final do jogo
            if ((partida1 == escolhaComputador) && (partida2 == escolhaComputador) && (partida3 == escolhaComputador) && (partida4 == escolhaComputador) && (partida5 == escolhaComputador)) {

                //Calcula os pontos de derrotas e vitórias
            } else if ((partida1 - escolhaComputador) == - 1 || (partida1 - escolhaComputador) == 2) {

                partida1++;
            } else if ((partida2 - escolhaComputador) == - 1 || (partida2 - escolhaComputador) == 2) {

                partida2++;
            } else if ((partida3 - escolhaComputador) == - 1 || (partida3 - escolhaComputador) == 2) {

                partida3++;
            } else if ((partida4 - escolhaComputador) == - 1 || (partida4 - escolhaComputador) == 2) {

                partida4++;
            } else if ((partida5 - escolhaComputador) == - 1 || (partida5 - escolhaComputador) == 2) {

                partida5++;

            } else {

                pontosComputador++;

            }

            if (partida1 > pontosComputador) {

                JOptionPane.showMessageDialog(jPanelJanela, "Usuário foi o vencedor do jogo. " + "\n\nUsuário " + " \nDerrotas: " + pontosComputador + " \nVitórias: " + partida1
                        + "\n\nComputador " + "\nDerrotas: " + pontosComputador + " \nVitórias: " + pontosComputador);

            } else if (partida2 > pontosComputador) {
                JOptionPane.showMessageDialog(jPanelJanela, "Usuário foi o vencedor do jogo. " + "\n\nUsuário " + " \nDerrotas: " + pontosComputador + " \nVitórias: " + partida2
                        + "\n\nComputador " + "\nDerrotas: " + pontosComputador + " \nVitórias: " + pontosComputador);

            } else if (partida3 > pontosComputador) {
                JOptionPane.showMessageDialog(jPanelJanela, "Usuário foi o vencedor do jogo. " + "\n\nUsuário " + " \nDerrotas: " + pontosComputador + " \nVitórias: " + partida3
                        + "\n\nComputador " + "\nDerrotas: " + pontosComputador + " \nVitórias: " + pontosComputador);

            } else if (partida4 > pontosComputador) {
                JOptionPane.showMessageDialog(jPanelJanela, "Usuário foi o vencedor do jogo. " + "\n\nUsuário " + " \nDerrotas: " + pontosComputador + " \nVitórias: " + partida4
                        + "\n\nComputador " + "\nDerrotas: " + pontosComputador + " \nVitórias: " + pontosComputador);

            } else if (partida5 > pontosComputador) {
                JOptionPane.showMessageDialog(jPanelJanela, "Computador vencedor do jogo. " + "\n\nUsuário " + " \nDerrotas: " + pontosComputador + " \nVitórias: " + partida5
                        + "\n\nComputador " + "\nDerrotas: " + pontosComputador + " \nVitórias: " + pontosComputador);

            } else if (partida1 < pontosComputador) {
                JOptionPane.showMessageDialog(jPanelJanela, "Computador vencedor do jogo. " + "\n\nUsuário " + " \nDerrotas: " + pontosComputador + " \nVitórias: " + partida1
                        + "\n\nComputador " + "\nDerrotas: " + pontosComputador + " \nVitórias: " + pontosComputador);
            } else if (partida2 < pontosComputador) {
                JOptionPane.showMessageDialog(jPanelJanela, "Computador vencedor do jogo. " + "\n\nUsuário " + " \nDerrotas: " + pontosComputador + " \nVitórias: " + partida2
                        + "\n\nComputador " + "\nDerrotas: " + pontosComputador + " \nVitórias: " + pontosComputador);
            } else if (partida3 < pontosComputador) {
                JOptionPane.showMessageDialog(jPanelJanela, "Computador vencedor do jogo. " + "\n\nUsuário " + " \nDerrotas: " + pontosComputador + " \nVitórias: " + partida3
                        + "\n\nComputador " + "\nDerrotas: " + pontosComputador + " \nVitórias: " + pontosComputador);
            } else if (partida4 < pontosComputador) {
                JOptionPane.showMessageDialog(jPanelJanela, "Computador vencedor do jogo. " + "\n\nUsuário " + " \nDerrotas: " + pontosComputador + " \nVitórias: " + partida4
                        + "\n\nComputador " + "\nDerrotas: " + pontosComputador + " \nVitórias: " + pontosComputador);

            } else if (partida5 < pontosComputador) {
                JOptionPane.showMessageDialog(jPanelJanela, "Computador vencedor do jogo. " + "\n\nUsuário " + " \nDerrotas: " + pontosComputador + " \nVitórias: " + partida5
                        + "\n\nComputador " + "\nDerrotas: " + pontosComputador + " \nVitórias: " + pontosComputador);

            } else {
                JOptionPane.showMessageDialog(jPanelJanela, "Empate entre os jogadores!" + "\n\nUsuário: " + " \nDerrotas: " + pontosComputador + " \nVitórias: " + partida1
                        + "\n\nComputador " + "\nDerrotas: " + pontosComputador + " \nVitórias: " + pontosComputador
                );
            }

        } catch (NumberFormatException e) {

        }


    }//GEN-LAST:event_jButtonJogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonJogar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelPartida1;
    private javax.swing.JLabel jLabelPartida2;
    private javax.swing.JLabel jLabelPartida3;
    private javax.swing.JLabel jLabelPartida4;
    private javax.swing.JLabel jLabelPartida5;
    private javax.swing.JLabel jLabelPergunta;
    private javax.swing.JPanel jPanelJanela;
    private javax.swing.JTextField jTextFieldPartida1;
    private javax.swing.JTextField jTextFieldPartida2;
    private javax.swing.JTextField jTextFieldPartida3;
    private javax.swing.JTextField jTextFieldPartida4;
    private javax.swing.JTextField jTextFieldPartida5;
    // End of variables declaration//GEN-END:variables
}
