
import java.security.SecureRandom;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Jussara Andrade
 */
public class Filme extends javax.swing.JFrame {

    int reco;

    public Filme() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadastroFilmes = new javax.swing.JPanel();
        jLabelNomeFilme = new javax.swing.JLabel();
        jTextFieldNomeFilme = new javax.swing.JTextField();
        jLabelNota = new javax.swing.JLabel();
        jButtonOk = new javax.swing.JButton();
        jButtonCadastroFilmesLimpar = new javax.swing.JButton();
        jComboBoxNotas = new javax.swing.JComboBox<>();
        jButtonFilmesAleatorios = new javax.swing.JButton();
        jPanelFilmesCadastrados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelCadastroFilmes.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro Filmes"));

        jLabelNomeFilme.setText("Nome do Filme:");

        jLabelNota.setText("Nota:");

        jButtonOk.setText("Cadastrar");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jButtonCadastroFilmesLimpar.setText("Limpar");
        jButtonCadastroFilmesLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroFilmesLimparActionPerformed(evt);
            }
        });

        jComboBoxNotas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jButtonFilmesAleatorios.setText("Recomendação");
        jButtonFilmesAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilmesAleatoriosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroFilmesLayout = new javax.swing.GroupLayout(jPanelCadastroFilmes);
        jPanelCadastroFilmes.setLayout(jPanelCadastroFilmesLayout);
        jPanelCadastroFilmesLayout.setHorizontalGroup(
            jPanelCadastroFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroFilmesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelCadastroFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroFilmesLayout.createSequentialGroup()
                        .addComponent(jButtonFilmesAleatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOk, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCadastroFilmesLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCadastroFilmesLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroFilmesLayout.createSequentialGroup()
                                .addComponent(jLabelNomeFilme)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNomeFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCadastroFilmesLayout.createSequentialGroup()
                                .addComponent(jLabelNota)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanelCadastroFilmesLayout.setVerticalGroup(
            jPanelCadastroFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroFilmesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelCadastroFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeFilme)
                    .addComponent(jTextFieldNomeFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNota)
                    .addComponent(jComboBoxNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOk)
                    .addComponent(jButtonCadastroFilmesLimpar)
                    .addComponent(jButtonFilmesAleatorios))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelFilmesCadastrados.setBorder(javax.swing.BorderFactory.createTitledBorder("Filmes Cadastrados"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Filmes", "Nota"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanelFilmesCadastradosLayout = new javax.swing.GroupLayout(jPanelFilmesCadastrados);
        jPanelFilmesCadastrados.setLayout(jPanelFilmesCadastradosLayout);
        jPanelFilmesCadastradosLayout.setHorizontalGroup(
            jPanelFilmesCadastradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
        );
        jPanelFilmesCadastradosLayout.setVerticalGroup(
            jPanelFilmesCadastradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCadastroFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelFilmesCadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelCadastroFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelFilmesCadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        if (jTextFieldNomeFilme.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Favor insira um nome de um filme!");
        } else {

            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

            String nome = jTextFieldNomeFilme.getText();
            String nota = (String) jComboBoxNotas.getSelectedItem();

            String[] novaLinha = {nome, nota};
            modelo.addRow(novaLinha);

        }

    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonFilmesAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilmesAleatoriosActionPerformed
       SecureRandom randomNumbers = new SecureRandom();
        int recomendacao = randomNumbers.nextInt(jTable1.getModel().getRowCount());

        JOptionPane.showMessageDialog(null, "Filmes aleatórios: \n"
                + "\n\n"
                + "Filme: " + (String) jTable1.getValueAt(recomendacao, 0) + "\n"
                + "Classificação: " + (String) jTable1.getValueAt(recomendacao, 1));


    }//GEN-LAST:event_jButtonFilmesAleatoriosActionPerformed

    private void jButtonCadastroFilmesLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroFilmesLimparActionPerformed

        jTextFieldNomeFilme.setText("");
        jComboBoxNotas.setSelectedIndex(0);

        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

        int deleta = 0;
        while (deleta < jTable1.getRowCount()) {
            modelo.removeRow(deleta);
        }

    }//GEN-LAST:event_jButtonCadastroFilmesLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Filme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Filme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Filme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Filme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Filme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastroFilmesLimpar;
    private javax.swing.JButton jButtonFilmesAleatorios;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JComboBox<String> jComboBoxNotas;
    private javax.swing.JLabel jLabelNomeFilme;
    private javax.swing.JLabel jLabelNota;
    private javax.swing.JPanel jPanelCadastroFilmes;
    private javax.swing.JPanel jPanelFilmesCadastrados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldNomeFilme;
    // End of variables declaration//GEN-END:variables
}
