
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Jussara Andrade
 */
public class Triangulo extends javax.swing.JFrame {

    float resultado;

    public Triangulo() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public void validação() {
        if ((jTextFieldCampoA.getText().length() > 0)
                && (jTextFieldCampoB.getText().length() > 0)
                && (jTextFieldCampoC.getText().length() > 0)) {

        } else {
            JOptionPane.showMessageDialog(null, "Confira os campos Obrigatórios!!");

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelJanela = new javax.swing.JPanel();
        jLabelValorA = new javax.swing.JLabel();
        jLabelValorB = new javax.swing.JLabel();
        jLabelValorC = new javax.swing.JLabel();
        jTextFieldCampoA = new javax.swing.JTextField();
        jTextFieldCampoB = new javax.swing.JTextField();
        jTextFieldCampoC = new javax.swing.JTextField();
        jButtonCalcular = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelJanela.setBorder(javax.swing.BorderFactory.createTitledBorder("Triângulo"));

        jLabelValorA.setText("Informe o valor do lado a:");

        jLabelValorB.setText("Informe o valor do lado b:");

        jLabelValorC.setText("Informe o valor do lado c:");

        jTextFieldCampoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCampoAActionPerformed(evt);
            }
        });

        jButtonCalcular.setText("Calcular");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        jButtonNovo.setText("Limpar");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelJanelaLayout = new javax.swing.GroupLayout(jPanelJanela);
        jPanelJanela.setLayout(jPanelJanelaLayout);
        jPanelJanelaLayout.setHorizontalGroup(
            jPanelJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJanelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelJanelaLayout.createSequentialGroup()
                        .addGroup(jPanelJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelValorB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelValorC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelValorA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCampoC)
                            .addComponent(jTextFieldCampoB)
                            .addGroup(jPanelJanelaLayout.createSequentialGroup()
                                .addComponent(jTextFieldCampoA, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(70, 70, 70))
                    .addGroup(jPanelJanelaLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))))
        );
        jPanelJanelaLayout.setVerticalGroup(
            jPanelJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJanelaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValorA)
                    .addComponent(jTextFieldCampoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValorB)
                    .addComponent(jTextFieldCampoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValorC)
                    .addComponent(jTextFieldCampoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanelJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCalcular)
                    .addComponent(jButton1)
                    .addComponent(jButtonNovo))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelJanela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelJanela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        validação();

        try {
            double a = Double.parseDouble(jTextFieldCampoA.getText());
            double b = Double.parseDouble(jTextFieldCampoB.getText());
            double c = Double.parseDouble(jTextFieldCampoC.getText());

            if ((c < a + b) && (b < c + a) && (a < c + b)) {
                if ((a == b) && (b == c)) {
                    JOptionPane.showMessageDialog(jPanelJanela, "O triângulo de lado " + a + " , " + b + " , " + c + " é eqüilátero", " \nTriângulo Equilátero", JOptionPane.INFORMATION_MESSAGE);

                } else {
                    if ((a == b) && (b == c) && (c == a)) {
                        JOptionPane.showMessageDialog(jPanelJanela, "O triângulo de lado " + a + " , " + b + " , " + c + " é escaleno", " \nTriângulo Escaleno", JOptionPane.INFORMATION_MESSAGE);

                    }
                    if ((a != b) && (b != c) && (c != a)) {
                        JOptionPane.showMessageDialog(jPanelJanela, "O triângulo de lado " + a + " , " + b + " , " + c + " é isóceles", " \nTriângulo Isóceles", JOptionPane.INFORMATION_MESSAGE);

                    }
                }
            } else {
                JOptionPane.showMessageDialog(jPanelJanela, "O triângulo de lado " + a + " , " + b + " , " + c + "\nNÃO é um triângulo", "Erro", JOptionPane.ERROR_MESSAGE);

            }

        } catch (NumberFormatException nfe) {

        }


    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jTextFieldCampoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCampoAActionPerformed


    }//GEN-LAST:event_jTextFieldCampoAActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        jTextFieldCampoA.setText("");
        jTextFieldCampoB.setText("");
        jTextFieldCampoC.setText("");
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(jPanelJanela, "Operação cancelada!");
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Triangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Triangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Triangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Triangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Triangulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelValorA;
    private javax.swing.JLabel jLabelValorB;
    private javax.swing.JLabel jLabelValorC;
    private javax.swing.JPanel jPanelJanela;
    private javax.swing.JTextField jTextFieldCampoA;
    private javax.swing.JTextField jTextFieldCampoB;
    private javax.swing.JTextField jTextFieldCampoC;
    // End of variables declaration//GEN-END:variables
}
